<?xml version="1.0" encoding="UTF-8"?>
<testsuite name="GreenTest"
           tests="11"
           failures="1"
           errors="0"
           skipped="0"
           time="10,516">
  <properties />
            <testcase name="FailTest" time="0,005" classname="GreenTest.FristClass">
                <failure type="java.lang.AssertionError"
                  message="expected [true] but found [false]"
              >
<![CDATA[java.lang.AssertionError: expected [true] but found [false]
  org.testng.Assert.fail(Assert.java:97)
  org.testng.Assert.failNotEquals(Assert.java:969)
  org.testng.Assert.assertTrue(Assert.java:43)
  org.testng.Assert.assertTrue(Assert.java:53)
  GreenTest.FristClass.FailTest(FristClass.java:128)
  java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
  java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
  java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
  java.base/java.lang.reflect.Method.invoke(Method.java:566)
  org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:134)
  org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:597)
  org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
  org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
  org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:816)
  org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
  org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
  org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
  java.base/java.util.ArrayList.forEach(ArrayList.java:1540)
  org.testng.TestRunner.privateRun(TestRunner.java:766)
  org.testng.TestRunner.run(TestRunner.java:587)
  org.testng.SuiteRunner.runTest(SuiteRunner.java:384)
  org.testng.SuiteRunner.runSequentially(SuiteRunner.java:378)
  org.testng.SuiteRunner.privateRun(SuiteRunner.java:337)
  org.testng.SuiteRunner.run(SuiteRunner.java:286)
  org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
  org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
  org.testng.TestNG.runSuitesSequentially(TestNG.java:1187)
  org.testng.TestNG.runSuitesLocally(TestNG.java:1109)
  org.testng.TestNG.runSuites(TestNG.java:1039)
  org.testng.TestNG.run(TestNG.java:1007)
  org.testng.IDEARemoteTestNG.run(IDEARemoteTestNG.java:73)
  org.testng.RemoteTestNGStarter.main(RemoteTestNGStarter.java:123)
]]>
      </failure>

          </testcase>
  
  
            <testcase name="TypeOnlyPassword4" time="0,207" classname="GreenTest.FristClass" />
                <testcase name="PageLoadWithoutCookies1" time="1,728" classname="GreenTest.FristClass" />
                <testcase name="PageLoadWithCookies7" time="0,871" classname="GreenTest.FristClass" />
                <testcase name="SignInAnotherButton9" time="0,079" classname="GreenTest.FristClass" />
                <testcase name="RememberButton10" time="2,560" classname="GreenTest.FristClass" />
                <testcase name="ClickButtonWithoudData2" time="0,117" classname="GreenTest.FristClass" />
                <testcase name="TypeOnlyLogin3" time="0,243" classname="GreenTest.FristClass" />
                <testcase name="InCorrectCredentials5" time="0,173" classname="GreenTest.FristClass" />
                <testcase name="CorrectCredentials6" time="4,435" classname="GreenTest.FristClass" />
                <testcase name="SignInCurrentButton8" time="0,098" classname="GreenTest.FristClass" />
      
</testsuite>
